### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'blockchain.mix_blockchain_network'

### ISSUE THREAD

**Issue by Smellyslab** [onuratakan/POW-Blockchain-Network-Infrustructure#1]
theres an error being thrown FileNotFoundError: [Errno 2] No such file or directory: 'blockchain.mix_blockchain_network'

**Comment by onuratakan** [comment]
If you create the blockchain, you will open the test mode after you will create the block with "cbc" command or clict to the"Create Blockchain" button.

This was a very experimental work of mine, it would be much better if you use the work at https://github.com/Decentra-Network/Decentra-Network instead, it is much more professional and stable.
